import type { CustomGroupId } from "@/lib/custom-catalog"
import type { FinishedProduct, Product } from "@/lib/mock-data"

type StoneRef = {
  name: string
  type: string
  origin: string
  quarry: string
  image: string
}

const IMG = {
  countertop: "/stonetrail_mock_assets/products/product-countertop-calacatta-luxury.jpg",
  bathroom: "/stonetrail_mock_assets/products/product-bathroom-pietra-grey.jpg",
  wall: "/stonetrail_mock_assets/products/product-wall-cladding-taj-mahal.jpg",
  stairs: "/stonetrail_mock_assets/products/product-stairs-bianco-carrara.jpg",
  fireplace: "/stonetrail_mock_assets/products/product-fireplace-emperador-dark.jpg",
  table: "/stonetrail_mock_assets/products/product-dining-table-verde-alpi.jpg",
  onyx: "/stonetrail_mock_assets/products/product-onyx-interior-honey.jpg",
  pool: "/stonetrail_mock_assets/products/product-pool-cladding-travertino-classico.jpg",
  slabCalacatta: "/stonetrail_mock_assets/slabs/calacatta-luxury-slab-01.jpg",
  slabCarrara: "/stonetrail_mock_assets/slabs/bianco-carrara-slab-01.jpg",
  slabTaj: "/stonetrail_mock_assets/slabs/taj-mahal-slab-01.jpg",
  slabVerde: "/stonetrail_mock_assets/slabs/verde-alpi-slab-01.jpg",
  slabNero: "/stonetrail_mock_assets/slabs/nero-marquina-slab-01.jpg",
  slabEmperador: "/stonetrail_mock_assets/slabs/emperador-dark-slab-01.jpg",
  slabBlue: "/stonetrail_mock_assets/slabs/blue-roma-slab-01.jpg",
  blockTrav: "/stonetrail_mock_assets/blocks/travertino-classico-block-01.jpg",
  blockNero: "/stonetrail_mock_assets/blocks/nero-marquina-block-01.jpg",
  blockTaj: "/stonetrail_mock_assets/blocks/taj-mahal-block-01.jpg",
  blockVerde: "/stonetrail_mock_assets/blocks/verde-alpi-block-01.jpg",
  granite: "/stone/black-granite.png",
  quartzite: "/stone/white-quartzite.png",
  travertine: "/stone/travertine.png",
  soapstone: "/stone/soapstone.png",
}

const STONE = {
  calacatta: { name: "Calacatta Luxury", type: "Мрамор", origin: "Каррара, Италия", quarry: "Каррара", image: "/stonetrail_mock_assets/stones/calacatta-luxury.jpg" },
  carrara: { name: "Bianco Carrara", type: "Мрамор", origin: "Каррара, Италия", quarry: "Каррара", image: "/stonetrail_mock_assets/stones/bianco-carrara.jpg" },
  tajMahal: { name: "Taj Mahal", type: "Кварцит", origin: "Баия, Бразилия", quarry: "Баия", image: "/stonetrail_mock_assets/stones/taj-mahal.jpg" },
  verdeAlpi: { name: "Verde Alpi", type: "Мрамор", origin: "Апуанские Альпы, Италия", quarry: "Alpi Apuane", image: "/stonetrail_mock_assets/stones/verde-alpi.jpg" },
  pietraGrey: { name: "Pietra Grey", type: "Известняк", origin: "Иран", quarry: "Исфахан", image: "/stonetrail_mock_assets/stones/pietra-grey.jpg" },
  emperador: { name: "Emperador Dark", type: "Известняк", origin: "Испания", quarry: "Бюхараго", image: "/stonetrail_mock_assets/stones/emperador-dark.jpg" },
  onice: { name: "Onice Honey", type: "Оникс", origin: "Иран", quarry: "Исфахан", image: "/stonetrail_mock_assets/stones/onice-honey.jpg" },
  travertine: { name: "Classic Travertine", type: "Травертин", origin: "Тиволи, Италия", quarry: "Tivoli", image: "/stonetrail_mock_assets/stones/travertino-classico.jpg" },
  nero: { name: "Nero Marquina", type: "Мрамор", origin: "Страна Басков, Испания", quarry: "Маркина", image: "/stonetrail_mock_assets/stones/nero-marquina.jpg" },
  crystal: { name: "Crystal White", type: "Мрамор", origin: "Греция", quarry: "Драма", image: "/stonetrail_mock_assets/stones/crystal-white.jpg" },
  portoro: { name: "Portoro Gold", type: "Мрамор", origin: "Лигурия, Италия", quarry: "Портовенере", image: "/stonetrail_mock_assets/stones/portoro-gold.jpg" },
  blueRoma: { name: "Blue Roma", type: "Кварцит", origin: "Баия, Бразилия", quarry: "Баия", image: "/stonetrail_mock_assets/stones/blue-roma.jpg" },
  blackGalaxy: { name: "Black Galaxy", type: "Гранит", origin: "Андхра-Прадеш, Индия", quarry: "Чиртоор", image: "/stone/black-granite.png" },
  absoluteBlack: { name: "Absolute Black", type: "Гранит", origin: "Раджастан, Индия", quarry: "Раджастан", image: "/stone/black-granite.png" },
  karelia: { name: "Габбро-диабаз", type: "Гранит", origin: "Карелия, Россия", quarry: "Карелия", image: "/stone/black-granite.png" },
  mansurov: { name: "Мансуровский", type: "Гранит", origin: "Башкортостан, Россия", quarry: "Мансурово", image: "/stone/white-quartzite.png" },
  jura: { name: "Jura Beige", type: "Известняк", origin: "Бавария, Германия", quarry: "Айхштетт", image: "/stone/soapstone.png" },
  sandstone: { name: "Дагестанский песчаник", type: "Песчаник", origin: "Дагестан, Россия", quarry: "Акуша", image: "/stone/travertine.png" },
} satisfies Record<string, StoneRef>

type Draft = {
  id: string
  slug: string
  name: string
  group: CustomGroupId
  productType: string
  stone: StoneRef
  description: string
  status: "В наличии" | "Под заказ"
  image: string
  images?: string[]
  dimensions?: string
  thickness?: string
  finish: string
  purpose: string
  height?: string
  diameter?: string
  format?: string
  applications: string[]
  characteristics?: Record<string, string>
  expertNote?: string
  price?: string
  priceType?: "on_request" | "fixed"
}

function toProduct(draft: Draft): FinishedProduct {
  const images = draft.images ?? [draft.image, draft.stone.image]
  return {
    id: draft.id,
    slug: draft.slug,
    category: "custom",
    name: draft.name,
    customGroup: draft.group,
    productType: draft.productType,
    stoneName: draft.stone.name,
    stoneType: draft.stone.type,
    origin: draft.stone.origin,
    quarry: draft.stone.quarry,
    stoneImage: draft.stone.image,
    description: draft.description,
    image: draft.image,
    images,
    status: draft.status,
    availability: draft.status,
    finish: draft.finish,
    dimensions: draft.dimensions,
    thickness: draft.thickness,
    height: draft.height,
    diameter: draft.diameter,
    format: draft.format,
    purpose: draft.purpose,
    applications: draft.applications,
    characteristics: draft.characteristics,
    expertNote: draft.expertNote,
    price: draft.price,
    priceType: draft.priceType ?? "on_request",
  }
}

const drafts: Draft[] = [
  {
    id: "fp-01",
    slug: "countertop-calacatta-luxury",
    name: "Кухонный остров с водопадом",
    group: "interior",
    productType: "Столешницы",
    stone: STONE.calacatta,
    description:
      "Демонстрационный пример: монолитная столешница с вертикальным свесом. Раскладка прожилки под bookmatching на широких плоскостях.",
    expertNote:
      "При проектировании столешницы слэб подбираем так, чтобы жила читалась на двух торцах симметрично. Для зоны готовки рекомендуем фартук из того же сорта.",
    dimensions: "2 400 × 1 200 × 90 мм",
    thickness: "30 мм",
    finish: "Полированная",
    status: "В наличии",
    image: IMG.countertop,
    purpose: "Кухня",
    applications: ["Кухонный остров", "Барная стойка", "Обеденная зона"],
    characteristics: { Кромка: "Еврозапил", Раскладка: "Bookmatching" },
  },
  {
    id: "fp-09",
    slug: "countertop-taj-mahal-kitchen",
    name: "Столешница с фартуком Taj Mahal",
    group: "interior",
    productType: "Столешницы",
    stone: STONE.tajMahal,
    description:
      "Демонстрационный пример кухонной столешницы из кварцита: рабочая плоскость и стеновой фартук из одного сорта.",
    dimensions: "3 200 × 650 × 30 мм",
    thickness: "30 мм",
    finish: "Сатинированная",
    status: "Под заказ",
    image: IMG.slabTaj,
    purpose: "Кухня",
    applications: ["Линейная кухня", "Фартук", "Подоконник-продолжение"],
  },
  {
    id: "fp-10",
    slug: "windowsill-carrara",
    name: "Подоконник Bianco Carrara",
    group: "interior",
    productType: "Подоконники",
    stone: STONE.carrara,
    description:
      "Демонстрационный подоконник из каррарского мрамора с капельником и полированной кромкой. Толщина подобрана под стандартный оконный проём.",
    dimensions: "1 800 × 350 мм",
    thickness: "30 мм",
    finish: "Полированная",
    status: "В наличии",
    image: IMG.slabCarrara,
    purpose: "Жилой интерьер",
    applications: ["Оконный проём", "Ниша", "Радиаторный короб"],
    characteristics: { Капельник: "Есть", Свес: "40 мм" },
  },
  {
    id: "fp-11",
    slug: "windowsill-pietra-grey",
    name: "Подоконник Pietra Grey",
    group: "interior",
    productType: "Подоконники",
    stone: STONE.pietraGrey,
    description:
      "Демонстрационный широкий подоконник из дымчатого известняка для панорамного остекления.",
    dimensions: "2 400 × 400 мм",
    thickness: "20 мм",
    finish: "Сатинированная",
    status: "Под заказ",
    image: IMG.bathroom,
    purpose: "Жилой интерьер",
    applications: ["Панорамное окно", "Французский балкон"],
  },
  {
    id: "fp-04",
    slug: "stairs-bianco-carrara",
    name: "Лестничный марш",
    group: "interior",
    productType: "Лестницы и ступени",
    stone: STONE.carrara,
    description:
      "Демонстрационный лестничный марш из белого каррарского мрамора: ступени 300 мм, полировка, фаска по краю.",
    expertNote:
      "Для маршей оставляем фаску 2–3 мм по кромке подъёма. Это снижает риск скола и спокойнее в эксплуатации, чем идеально острые кромки.",
    dimensions: "14 ступеней, ширина 1 100 мм",
    thickness: "30 мм",
    finish: "Полированная",
    status: "В наличии",
    image: IMG.stairs,
    purpose: "Жилой интерьер",
    applications: ["Внутренняя лестница", "Холл", "Парадное крыльцо"],
    characteristics: { Фаска: "3 мм", "Количество ступеней": "14" },
  },
  {
    id: "fp-12",
    slug: "stairs-granite-absolute",
    name: "Ступени Absolute Black",
    group: "interior",
    productType: "Лестницы и ступени",
    stone: STONE.absoluteBlack,
    description:
      "Демонстрационные накладные ступени из чёрного гранита для входной группы с интенсивной нагрузкой.",
    dimensions: "1 200 × 350 мм",
    thickness: "30 мм",
    finish: "Термообработанная",
    status: "Под заказ",
    image: IMG.granite,
    purpose: "Входная группа",
    applications: ["Входная лестница", "Цоколь", "Площадка"],
  },
  {
    id: "fp-05",
    slug: "fireplace-emperador-dark",
    name: "Каминный портал",
    group: "interior",
    productType: "Камины",
    stone: STONE.emperador,
    description:
      "Демонстрационный портал камина в тёмном известняке с золотисто-серыми жилками. Сатин без агрессивного глянца.",
    expertNote:
      "Термостойкость известняка достаточна при расстоянии от горелки 150–200 мм. Сатин лучше держит жар, чем полировка.",
    dimensions: "1 800 × 1 200 × 600 мм",
    finish: "Сатинированная",
    status: "В наличии",
    image: IMG.fireplace,
    purpose: "Гостиная",
    applications: ["Каминный портал", "Облицовка топки", "Каминная полка"],
  },
  {
    id: "fp-02",
    slug: "bathroom-pietra-grey",
    name: "Ванная из цельного камня",
    group: "interior",
    productType: "Мойки и ванны",
    stone: STONE.pietraGrey,
    description:
      "Демонстрационный санузел: стены, пол и подиум из одного сорта известняка. Шлифованная поверхность безопаснее во влажной зоне.",
    expertNote:
      "Известняк хорошо работает при гидрофобизации. На пол ставим шлифованный формат, а не полированный.",
    dimensions: "площадь облицовки 28 м²",
    finish: "Шлифованная",
    status: "Под заказ",
    image: IMG.bathroom,
    purpose: "Ванная",
    applications: ["Чаша ванны", "Облицовка стен", "Подиум"],
  },
  {
    id: "fp-13",
    slug: "sink-verde-alpi",
    name: "Накладная мойка Verde Alpi",
    group: "interior",
    productType: "Мойки и ванны",
    stone: STONE.verdeAlpi,
    description:
      "Демонстрационная цельная мойка из зелёного мрамора для кухни или барной зоны.",
    dimensions: "550 × 400 × 200 мм",
    thickness: "20 мм",
    finish: "Полированная",
    status: "Под заказ",
    image: IMG.table,
    purpose: "Кухня",
    applications: ["Кухонная мойка", "Барная мойка"],
  },
  {
    id: "fp-03",
    slug: "wall-cladding-taj-mahal",
    name: "Панно-экран из камня",
    group: "interior",
    productType: "Мозаика",
    stone: STONE.tajMahal,
    description:
      "Демонстрационная акцентная стена: вертикальная раскладка широких панелей с тёплым серо-бежевым рисунком.",
    expertNote:
      "Для стен со средним рисунком выбираем вертикальный монтаж — рисунок вытягивает пространство.",
    dimensions: "3 800 × 2 700 мм",
    format: "600 × 300 мм",
    finish: "Сатинированная",
    status: "В наличии",
    image: IMG.wall,
    purpose: "Гостиная",
    applications: ["Акцентная стена", "ТВ-зона", "Холл"],
  },
  {
    id: "fp-07",
    slug: "onyx-interior-honey",
    name: "Световая мозаика из оникса",
    group: "interior",
    productType: "Мозаика",
    stone: STONE.onice,
    description:
      "Демонстрационные светопрозрачные панели из медового оникса. Тонкая нарезка усиливает опалесценцию при подсветке.",
    expertNote:
      "Оникс ставим только там, где есть гарантированная подсветка. Без неё опалесценция гаснет.",
    dimensions: "1 200 × 600 × 8 мм",
    format: "300 × 300 мм",
    finish: "Полированная",
    status: "Под заказ",
    image: IMG.onyx,
    purpose: "Декор интерьера",
    applications: ["Подсвеченная ниша", "Барный фасад", "Перегородка"],
  },
  {
    id: "fp-14",
    slug: "carving-portoro",
    name: "Резной фриз Portoro Gold",
    group: "interior",
    productType: "Художественная резьба",
    stone: STONE.portoro,
    description:
      "Демонстрационный резной фриз из чёрного мрамора с золотистой жилкой. Ручная выборка орнамента.",
    dimensions: "1 800 × 220 мм",
    thickness: "40 мм",
    finish: "Полированная",
    status: "Под заказ",
    image: IMG.slabNero,
    purpose: "Парадный интерьер",
    applications: ["Карниз", "Портал", "Мебельный фасад"],
    characteristics: { Техника: "Ручная резьба", Рельеф: "2–8 мм" },
  },
  {
    id: "fp-15",
    slug: "relief-carrara",
    name: "Барельеф Bianco Carrara",
    group: "interior",
    productType: "Барельефы",
    stone: STONE.carrara,
    description:
      "Демонстрационный барельеф для акцентной стены. Глубина рельефа подобрана так, чтобы рисунок читался при боковом свете.",
    dimensions: "1 400 × 900 мм",
    thickness: "50 мм",
    finish: "Сатинированная",
    status: "Под заказ",
    image: IMG.slabCarrara,
    purpose: "Гостиная",
    applications: ["Акцентная стена", "Лестничный пролёт", "Каминный фронтон"],
  },
  {
    id: "fp-08",
    slug: "pool-terrace-travertine",
    name: "Плиты мощения у воды",
    group: "exterior",
    productType: "Плиты мощения",
    stone: STONE.travertine,
    description:
      "Демонстрационные плиты мощения из травертина для террасы у бассейна. Шлифованная поверхность, тёплый полосчатый рисунок.",
    expertNote:
      "Травертин для зон у воды: естественная пористость не боится хлора, тёплые тона визуально осветляют площадку.",
    format: "600 × 600 мм",
    thickness: "30 мм",
    finish: "Шлифованная",
    status: "В наличии",
    image: IMG.pool,
    purpose: "Терраса",
    applications: ["Терраса у бассейна", "Садовая площадка", "Двор"],
  },
  {
    id: "fp-16",
    slug: "paving-slab-jura",
    name: "Плита мощения Jura Beige",
    group: "exterior",
    productType: "Плиты мощения",
    stone: STONE.jura,
    description:
      "Демонстрационная крупноформатная плита мощения из юрского известняка для входных групп.",
    format: "800 × 800 мм",
    thickness: "40 мм",
    finish: "Термообработанная",
    status: "Под заказ",
    image: IMG.soapstone,
    purpose: "Входная группа",
    applications: ["Парадный двор", "Пешеходная зона"],
  },
  {
    id: "fp-17",
    slug: "custom-paving-karelia",
    name: "Брусчатка габбро-диабаз",
    group: "exterior",
    productType: "Брусчатка",
    stone: STONE.karelia,
    description:
      "Демонстрационная гранитная брусчатка из карельского габбро-диабаза. Колотая фактура для дорожек и дворов.",
    format: "100 × 100 мм",
    thickness: "60 мм",
    finish: "Колотая",
    status: "В наличии",
    image: IMG.blockNero,
    purpose: "Дорожки",
    applications: ["Садовая дорожка", "Двор", "Парковка"],
  },
  {
    id: "fp-18",
    slug: "curb-mansurov",
    name: "Бордюр Мансуровский",
    group: "exterior",
    productType: "Бордюры",
    stone: STONE.mansurov,
    description:
      "Демонстрационный гранитный бордюр светлого тона для отделения мощения и газона.",
    dimensions: "1 000 × 150 × 300 мм",
    thickness: "80 мм",
    finish: "Пиленая",
    status: "В наличии",
    image: IMG.quartzite,
    purpose: "Благоустройство",
    applications: ["Окантовка дорожек", "Газон", "Площадь"],
  },
  {
    id: "fp-19",
    slug: "tactile-granite",
    name: "Тактильная плита Absolute Black",
    group: "exterior",
    productType: "Тактильные плиты",
    stone: STONE.absoluteBlack,
    description:
      "Демонстрационная тактильная плита с рифами для входных групп и общественных пространств.",
    format: "300 × 300 мм",
    thickness: "30 мм",
    finish: "Термообработанная",
    status: "Под заказ",
    image: IMG.granite,
    purpose: "Общественное пространство",
    applications: ["Вход в здание", "Пешеходный переход", "Платформа"],
    characteristics: { Рисунок: "Конусы", "Норматив": "Демо-образец" },
  },
  {
    id: "fp-20",
    slug: "channel-granite",
    name: "Водоприемный лоток из гранита",
    group: "exterior",
    productType: "Водоприемные лотки",
    stone: STONE.blackGalaxy,
    description:
      "Демонстрационный гранитный лоток для отвода воды с мощения. Решётка в том же сорте.",
    dimensions: "1 000 × 150 × 80 мм",
    finish: "Пиленая",
    status: "Под заказ",
    image: IMG.blockNero,
    purpose: "Дренаж",
    applications: ["Терраса", "Площадка у входа", "Пандус"],
  },
  {
    id: "fp-21",
    slug: "massive-step-karelia",
    name: "Массивная ступень габбро-диабаз",
    group: "exterior",
    productType: "Массивные ступени",
    stone: STONE.karelia,
    description:
      "Демонстрационная цельная уличная ступень большой толщины. Без накладного слоя — камень работает как несущий элемент.",
    dimensions: "1 500 × 400 × 150 мм",
    thickness: "150 мм",
    finish: "Термообработанная",
    status: "Под заказ",
    image: IMG.granite,
    purpose: "Входная группа",
    applications: ["Крыльцо", "Садовая лестница", "Терраса"],
  },
  {
    id: "fp-22",
    slug: "cladding-tile-travertine",
    name: "Облицовочная плитка Classic Travertine",
    group: "facades",
    productType: "Облицовочная плитка",
    stone: STONE.travertine,
    description:
      "Демонстрационная фасадная плитка из травертина для цоколя и стен малоэтажных зданий.",
    format: "600 × 300 мм",
    thickness: "20 мм",
    finish: "Шлифованная",
    status: "В наличии",
    image: IMG.travertine,
    purpose: "Фасад",
    applications: ["Цоколь", "Дворовой фасад", "Колоннада"],
  },
  {
    id: "fp-23",
    slug: "cladding-tile-sandstone",
    name: "Облицовочная плитка из песчаника",
    group: "facades",
    productType: "Облицовочная плитка",
    stone: STONE.sandstone,
    description:
      "Демонстрационная облицовочная плитка из дагестанского песчаника. Тёплая фактура для частных фасадов.",
    format: "400 × 200 мм",
    thickness: "20 мм",
    finish: "Пиленая",
    status: "Под заказ",
    image: IMG.blockTrav,
    purpose: "Фасад",
    applications: ["Частный дом", "Забор", "Цоколь"],
  },
  {
    id: "fp-24",
    slug: "facade-slab-jura",
    name: "Фасадная плита Jura Beige",
    group: "facades",
    productType: "Фасадные плиты",
    stone: STONE.jura,
    description:
      "Демонстрационная крупноформатная фасадная плита из юрского известняка. Спокойный бежевый тон для сплошной облицовки.",
    format: "1 200 × 600 мм",
    thickness: "30 мм",
    finish: "Шлифованная",
    status: "Под заказ",
    image: IMG.soapstone,
    purpose: "Фасад",
    applications: ["Навесная облицовка", "Цоколь", "Козырёк"],
  },
  {
    id: "fp-25",
    slug: "ventilated-granite",
    name: "Плита вентфасада Absolute Black",
    group: "facades",
    productType: "Плиты для вентфасадов",
    stone: STONE.absoluteBlack,
    description:
      "Демонстрационная плита под систему вентилируемого фасада. Калибровка под скрытый крепёж.",
    format: "1 200 × 600 мм",
    thickness: "30 мм",
    finish: "Полированная",
    status: "Под заказ",
    image: IMG.granite,
    purpose: "Вентфасад",
    applications: ["Офисный фасад", "Цоколь здания", "Колонны"],
    characteristics: { Крепёж: "Скрытый", Калибровка: "±1 мм" },
  },
  {
    id: "fp-26",
    slug: "split-stone-sandstone",
    name: "Колотый камень дагестанский",
    group: "facades",
    productType: "Фактурный / колотый камень",
    stone: STONE.sandstone,
    description:
      "Демонстрационный фактурный камень с колотой лицевой гранью. Для цоколей, заборов и акцентов на фасаде.",
    thickness: "30–50 мм",
    finish: "Колотая",
    status: "В наличии",
    image: IMG.blockTrav,
    purpose: "Фасад",
    applications: ["Цоколь", "Забор", "Подпорная стена"],
  },
  {
    id: "fp-27",
    slug: "column-carrara",
    name: "Колонна Bianco Carrara",
    group: "architectural",
    productType: "Колонны",
    stone: STONE.carrara,
    description:
      "Демонстрационная круглая колонна из каррарского мрамора с дорической капителью.",
    height: "2 800 мм",
    diameter: "350 мм",
    finish: "Полированная",
    status: "Под заказ",
    image: IMG.slabCarrara,
    purpose: "Парадный интерьер",
    applications: ["Холл", "Портик", "Галерея"],
    characteristics: { Капитель: "Дорическая", Ствол: "Монолитный" },
  },
  {
    id: "fp-28",
    slug: "column-granite",
    name: "Колонна габбро-диабаз",
    group: "architectural",
    productType: "Колонны",
    stone: STONE.karelia,
    description:
      "Демонстрационная уличная колонна из карельского гранита. Термообработка для эксплуатации на улице.",
    height: "3 200 мм",
    diameter: "450 мм",
    finish: "Термообработанная",
    status: "Под заказ",
    image: IMG.granite,
    purpose: "Экстерьер",
    applications: ["Портик", "Терраса", "Ограда"],
  },
  {
    id: "fp-29",
    slug: "balustrade-crystal",
    name: "Балюстрада Crystal White",
    group: "architectural",
    productType: "Балюстрады",
    stone: STONE.crystal,
    description:
      "Демонстрационный комплект балюстрады: поручень, балясины и основание из одного сорта.",
    height: "900 мм",
    finish: "Полированная",
    status: "Под заказ",
    image: IMG.slabCalacatta,
    purpose: "Терраса",
    applications: ["Балкон", "Терраса", "Лестница"],
    characteristics: { Шаг: "180 мм", Комплект: "Поручень, балясины, цоколь" },
  },
  {
    id: "fp-30",
    slug: "baluster-carrara",
    name: "Балясина Bianco Carrara",
    group: "architectural",
    productType: "Балясины",
    stone: STONE.carrara,
    description:
      "Демонстрационная точёная балясина классического профиля. Поставляется комплектом под длину марша.",
    height: "800 мм",
    diameter: "140 мм",
    finish: "Полированная",
    status: "В наличии",
    image: IMG.stairs,
    purpose: "Лестница",
    applications: ["Лестничный марш", "Балюстрада", "Терраса"],
  },
  {
    id: "fp-31",
    slug: "railing-pietra-grey",
    name: "Перила Pietra Grey",
    group: "architectural",
    productType: "Перила",
    stone: STONE.pietraGrey,
    description:
      "Демонстрационный каменный поручень для лестницы. Скрытое крепление к металлическому каркасу.",
    dimensions: "длина секции 1 500 мм",
    height: "900 мм",
    finish: "Сатинированная",
    status: "Под заказ",
    image: IMG.bathroom,
    purpose: "Лестница",
    applications: ["Внутренняя лестница", "Пандус", "Галерея"],
  },
  {
    id: "fp-32",
    slug: "fountain-travertine",
    name: "Фонтан Classic Travertine",
    group: "architectural",
    productType: "Фонтаны",
    stone: STONE.travertine,
    description:
      "Демонстрационная чаша фонтана из травертина для внутреннего двора. Чаша и постамент из одного блока.",
    height: "1 200 мм",
    diameter: "1 400 мм",
    finish: "Шлифованная",
    status: "Под заказ",
    image: IMG.pool,
    purpose: "Двор",
    applications: ["Внутренний двор", "Сад", "Холл"],
  },
  {
    id: "fp-33",
    slug: "planter-sandstone",
    name: "Вазон из песчаника",
    group: "architectural",
    productType: "Вазоны",
    stone: STONE.sandstone,
    description:
      "Демонстрационный садовый вазон из дагестанского песчаника. Толстые стенки, дренажное отверстие.",
    height: "650 мм",
    diameter: "700 мм",
    finish: "Пиленая",
    status: "В наличии",
    image: IMG.blockTrav,
    purpose: "Сад",
    applications: ["Сад", "Терраса", "Входная группа"],
  },
  {
    id: "fp-34",
    slug: "bench-granite",
    name: "Скамья габбро-диабаз",
    group: "architectural",
    productType: "Скамьи",
    stone: STONE.karelia,
    description:
      "Демонстрационная уличная скамья из карельского гранита. Сиденье термообработано, боковины пиленые.",
    dimensions: "1 800 × 450 × 450 мм",
    finish: "Термообработанная",
    status: "В наличии",
    image: IMG.granite,
    purpose: "Общественное пространство",
    applications: ["Парк", "Двор", "Набережная"],
  },
  {
    id: "fp-35",
    slug: "bench-travertine",
    name: "Садовая скамья из травертина",
    group: "architectural",
    productType: "Скамьи",
    stone: STONE.travertine,
    description:
      "Демонстрационная садовая скамья тёплого тона. Для частных дворов и террас.",
    dimensions: "1 600 × 400 × 420 мм",
    finish: "Шлифованная",
    status: "Под заказ",
    image: IMG.blockTaj,
    purpose: "Сад",
    applications: ["Сад", "Терраса"],
  },
  {
    id: "fp-36",
    slug: "small-form-sphere",
    name: "Садовая сфера из гранита",
    group: "architectural",
    productType: "Другие малые архитектурные формы",
    stone: STONE.mansurov,
    description:
      "Демонстрационная малая форма: гранитная сфера для сада и входной группы.",
    diameter: "400 мм",
    finish: "Полированная",
    status: "Под заказ",
    image: IMG.quartzite,
    purpose: "Сад",
    applications: ["Сад", "Входная группа", "Партер"],
  },
  {
    id: "fp-37",
    slug: "monument-karelia",
    name: "Памятник габбро-диабаз",
    group: "memorial",
    productType: "Памятники",
    stone: STONE.karelia,
    description:
      "Демонстрационный вертикальный памятник из карельского габбро-диабаза. Полированный лицевой фасад, торцы термообработаны.",
    dimensions: "1 200 × 600 × 80 мм",
    finish: "Полированная",
    status: "В наличии",
    image: IMG.granite,
    purpose: "Мемориал",
    applications: ["Одиночный памятник", "Семейный участок"],
  },
  {
    id: "fp-38",
    slug: "monument-mansurov",
    name: "Памятник Мансуровский",
    group: "memorial",
    productType: "Памятники",
    stone: STONE.mansurov,
    description:
      "Демонстрационный светлый гранитный памятник. Спокойный тон для участков, где чёрный камень визуально тяжёл.",
    dimensions: "1 000 × 500 × 80 мм",
    finish: "Полированная",
    status: "Под заказ",
    image: IMG.quartzite,
    purpose: "Мемориал",
    applications: ["Одиночный памятник", "Семейный участок"],
  },
  {
    id: "fp-43",
    slug: "fireplace-nero-marquina",
    name: "Каминный портал Nero Marquina",
    group: "interior",
    productType: "Камины",
    stone: STONE.nero,
    description:
      "Демонстрационный каминный портал из чёрного мрамора с белой жилкой. Контрастный акцент для гостиной.",
    dimensions: "1 600 × 1 100 × 400 мм",
    finish: "Полированная",
    status: "Под заказ",
    image: IMG.slabNero,
    purpose: "Гостиная",
    applications: ["Каминный портал", "Каминная полка"],
  },
  {
    id: "fp-44",
    slug: "relief-onice",
    name: "Барельеф Onice Honey",
    group: "interior",
    productType: "Барельефы",
    stone: STONE.onice,
    description:
      "Демонстрационный подсвечиваемый барельеф из оникса. Рельеф читается при контровом свете.",
    dimensions: "1 000 × 700 мм",
    thickness: "40 мм",
    finish: "Полированная",
    status: "Под заказ",
    image: IMG.onyx,
    purpose: "Декор интерьера",
    applications: ["Акцентная стена", "Ниша"],
  },
  {
    id: "fp-45",
    slug: "curb-karelia",
    name: "Бордюр габбро-диабаз",
    group: "exterior",
    productType: "Бордюры",
    stone: STONE.karelia,
    description:
      "Демонстрационный тёмный гранитный бордюр для общественных пространств и проездов.",
    dimensions: "1 000 × 180 × 300 мм",
    thickness: "80 мм",
    finish: "Пиленая",
    status: "В наличии",
    image: IMG.granite,
    purpose: "Благоустройство",
    applications: ["Площадь", "Проезд", "Дорожка"],
  },
  {
    id: "fp-46",
    slug: "massive-step-jura",
    name: "Массивная ступень Jura Beige",
    group: "exterior",
    productType: "Массивные ступени",
    stone: STONE.jura,
    description:
      "Демонстрационная цельная ступень из юрского известняка для садовой лестницы.",
    dimensions: "1 400 × 380 × 140 мм",
    thickness: "150 мм",
    finish: "Шлифованная",
    status: "Под заказ",
    image: IMG.soapstone,
    purpose: "Сад",
    applications: ["Садовая лестница", "Терраса"],
  },
  {
    id: "fp-47",
    slug: "facade-slab-travertine",
    name: "Фасадная плита Classic Travertine",
    group: "facades",
    productType: "Фасадные плиты",
    stone: STONE.travertine,
    description:
      "Демонстрационная фасадная плита из травертина. Тёплый тон для сплошной облицовки малоэтажного фасада.",
    format: "1 200 × 600 мм",
    thickness: "30 мм",
    finish: "Шлифованная",
    status: "В наличии",
    image: IMG.travertine,
    purpose: "Фасад",
    applications: ["Навесная облицовка", "Цоколь"],
  },
  {
    id: "fp-48",
    slug: "ventilated-jura",
    name: "Плита вентфасада Jura Beige",
    group: "facades",
    productType: "Плиты для вентфасадов",
    stone: STONE.jura,
    description:
      "Демонстрационная плита вентфасада из известняка. Калибровка под скрытый крепёж.",
    format: "800 × 400 мм",
    thickness: "30 мм",
    finish: "Шлифованная",
    status: "Под заказ",
    image: IMG.soapstone,
    purpose: "Вентфасад",
    applications: ["Офисный фасад", "Цоколь здания"],
  },
  {
    id: "fp-49",
    slug: "railing-carrara",
    name: "Перила Bianco Carrara",
    group: "architectural",
    productType: "Перила",
    stone: STONE.carrara,
    description:
      "Демонстрационный полированный поручень из каррарского мрамора для внутренней лестницы.",
    dimensions: "длина секции 1 200 мм",
    height: "900 мм",
    finish: "Полированная",
    status: "В наличии",
    image: IMG.stairs,
    purpose: "Лестница",
    applications: ["Внутренняя лестница", "Галерея"],
  },
  {
    id: "fp-50",
    slug: "planter-travertine",
    name: "Вазон Classic Travertine",
    group: "architectural",
    productType: "Вазоны",
    stone: STONE.travertine,
    description:
      "Демонстрационный вазон из травертина для террасы и внутреннего двора.",
    height: "500 мм",
    diameter: "600 мм",
    finish: "Шлифованная",
    status: "Под заказ",
    image: IMG.pool,
    purpose: "Терраса",
    applications: ["Терраса", "Двор"],
  },
  {
    id: "fp-51",
    slug: "small-form-bollard",
    name: "Парковочный столбик из гранита",
    group: "architectural",
    productType: "Другие малые архитектурные формы",
    stone: STONE.absoluteBlack,
    description:
      "Демонстрационная малая форма: гранитный столбик для ограничения проезда.",
    height: "600 мм",
    diameter: "180 мм",
    finish: "Термообработанная",
    status: "В наличии",
    image: IMG.granite,
    purpose: "Благоустройство",
    applications: ["Двор", "Парковка", "Входная группа"],
  },
  {
    id: "fp-52",
    slug: "stele-karelia",
    name: "Стела габбро-диабаз",
    group: "memorial",
    productType: "Стелы",
    stone: STONE.karelia,
    description:
      "Демонстрационная вертикальная стела из карельского гранита. Лицевая плоскость под гравировку.",
    height: "2 400 мм",
    dimensions: "2 400 × 600 × 120 мм",
    finish: "Полированная",
    status: "В наличии",
    image: IMG.granite,
    purpose: "Мемориал",
    applications: ["Мемориальный парк", "Сквер"],
  },
]

const extraDrafts: Draft[] = [
  {
    id: "fp-40",
    slug: "pedestal-absolute-black",
    name: "Постамент Absolute Black",
    group: "memorial",
    productType: "Постаменты",
    stone: STONE.absoluteBlack,
    description:
      "Демонстрационный постамент под скульптуру или стелу. Скрытые закладные, калиброванная верхняя плоскость.",
    dimensions: "800 × 800 × 600 мм",
    height: "600 мм",
    finish: "Полированная",
    status: "Под заказ",
    image: IMG.blockNero,
    purpose: "Мемориал",
    applications: ["Памятник", "Скульптура", "Стела"],
  },
  {
    id: "fp-41",
    slug: "stele-mansurov",
    name: "Стела Мансуровский гранит",
    group: "memorial",
    productType: "Стелы",
    stone: STONE.mansurov,
    description:
      "Демонстрационная вертикальная стела. Лицевая плоскость под гравировку, тыльная — шлифовка.",
    height: "2 200 мм",
    dimensions: "2 200 × 700 × 100 мм",
    finish: "Полированная",
    status: "Под заказ",
    image: IMG.quartzite,
    purpose: "Мемориал",
    applications: ["Мемориальный парк", "Сквер", "Участок"],
  },
  {
    id: "fp-42",
    slug: "memorial-complex-karelia",
    name: "Мемориальный комплекс габбро-диабаз",
    group: "memorial",
    productType: "Мемориальные комплексы",
    stone: STONE.karelia,
    description:
      "Демонстрационный комплекс: стела, цветник и надгробная плита из одного сорта. Единая фактура и тон.",
    finish: "Полированная / термообработанная",
    status: "Под заказ",
    image: IMG.granite,
    purpose: "Мемориал",
    applications: ["Семейный участок", "Закрытый мемориал"],
    characteristics: { Состав: "Стела, цветник, плита", Цоколь: "Термообработка" },
  },
]

export const finishedProducts: FinishedProduct[] = [...drafts, ...extraDrafts].map(toProduct)
